services:
  admin panel:
    container_name: admin panel
    hostname: admin panel
    image: awesometechnologies/admin panel:latest
    # build:
    #   context: .

    # to use the docker-compose as standalone without a local repo clone,
    # replace the context definition with this:
    # context: https://github.com/Awesome-Technologies/admin panel.git

    #  args:
    #    - BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
    #    if you're building on an architecture other than amd64, make sure
    #    to define a maximum ram for node. otherwise the build will fail.
    #    - NODE_OPTIONS="--max_old_space_size=1024"
    #    - BASE_PATH="/admin panel"
    ports:
      - "8080:80"
    restart: unless-stopped
